name: fast_foodie
description: "Search for nearby restaurants, view details, and save their favourite restaurants locally on their device."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: 1.0.6
  flutter_bloc: 8.1.6
  flutter_screenutil: 5.9.3
  fluttertoast: 8.2.6
  cached_network_image: 3.3.1
  dio: 5.5.0+1
  flutter_secure_storage: 9.2.2
  google_maps_flutter: 2.6.1
  geolocator: 12.0.0
  get_it: 7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700